### ISSUE TITLE
missing Requirement.txt and README

### ISSUE THREAD

**Issue by AyeshaIrshad1337** [MuneerRaza/DDPM_dlp_project#1]
Kindly add a requirement.txt file so i know which library and there version to download .. and also your python version ....  and the README.md file so i can understand the project you have build :)

**Comment by MuneerRaza** [comment]
It is under construction 🚧 :)

**Comment by AyeshaIrshad1337** [comment]
can i charge treat for it xd ?

**Comment by MuneerRaza** [comment]
😂😂😂

**Comment by AyeshaIrshad1337** [comment]
pljjjjjjjjjjjjjjjjjjjjjjjj brother ... but not from you ... from rafay xd
